name: CI

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - 2.3
          - 2.4
          - 2.5
          - 2.6
          - 2.7
          - jruby-9.2.9.0
          - ruby-head
          - jruby-head
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "${{ matrix.ruby-version }}"
          bundler-cache: true
      - name: Run spec
        run: bundle exec rake
